# Default values for OCB Auth
replicaCount: 1

image:
  repository: image-registry.openshift-image-registry.svc:5000/ciam/ocb-auth
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "ocb-auth"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi